/* AUTH */
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_SUCCESS_FAILURE";

export const AUTH_SIGNUP = "AUTH_SIGNUP";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_SUCCESS_FAILURE";

export const AUTH_VALIDATE_TOKEN = "AUTH_VALIDATE_TOKEN";
export const AUTH_VALIDATE_TOKEN_SUCCESS = "AUTH_VALIDATE_TOKEN_SUCCESS";
export const AUTH_VALIDATE_TOKEN_FAILURE = "AUTH_VALIDATE_TOKEN_FAILURE";

export const AUTH_TOGGLE_ACTION = "AUTH_TOGGLE_ACTION";
